# docker-compose to deploy this app with dockerfile
version: '3.7'
services:
  app:
    build: .
    ports:
      - "${PORT}:8080"
    volumes:
      - .:/app
    restart: unless-stopped
    environment:
      - PORT
      - DB_URL
      - PARAMS